### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/ArcticEcho/Phamhilator

This was requested by a real person (user ArcticEcho) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by ProgramFOX** [comment]
Cool!

**Comment by ArcticEcho** [comment]
Yeah, @Vincentyification [mentioned it](http://chat.stackoverflow.com/transcript/message/21393192#21393192), so I'd take a look. :D

**Comment by Vincentyification** [comment]
Hooray for moving onto Waffle integration :D

**Comment by ArcticEcho** [comment]
\o/

**Pull request merged**
